version: "3"
services:
  app:
    image: ${BACKEND_IMAGE:-thecntgfy/libooker:prod}
    environment:
      POSTGRES_DB: ${DB_NAME:-libooker}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-5d7gTKzS}
      DOWNLOAD_USERS_URL: ${DOWNLOAD_USERS_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-libooker}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-5d7gTKzS}

  nginx:
    image: nginx:stable
    volumes:
      - ${NGINX_CONFIG_PATH:-./docker/nginx.conf}:/etc/nginx/nginx.conf
      - ${NGINX_DATA_PATH:-/www/data}:/www/data
    ports:
      - "80:80"
    depends_on:
      - app