spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/libooker"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
      instance:
        metadata:
          user: ${spring.security.user.name}
          password: ${spring.security.user.password}
  devtools:
    restart:
      log-condition-evaluation-delta: false
server:
  error:
    include-stacktrace: never
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: libooker.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
app:
  jwtExpirationInMs: 86400000
  jwtSecret: ${JWT_SECRET}
  downloadUsersUrl: ${DOWNLOAD_USERS_URL}