name: Build prod

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: thecntgfy/libooker:latest
          cache-from: type=registry,ref=thecntgfy/libooker:prod
          cache-to: type=inline